const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const q=id=>document.getElementById(id);
function labels(locale){return locale==='en'?{
 eyebrow:'INTERACTIVE OOP MODEL',step:'Step',prev:'Previous',next:'Next',reset:'Reset',type:'Type model',object:'Runtime object',iface:'Base interface',privateState:'private state',publicApi:'public interface',baseRef:'base reference',notBound:'not bound',dispatch:'virtual dispatch',experiment:'Free experiment',deposit:'deposit(+100)',withdraw:'withdraw(-50)',call:'view.kind()',direct:'bonus.balance = 0',blocked:'Rejected: balance is private',same:'same object',note:'Concept model'
}:{eyebrow:'ИНТЕРАКТИВНАЯ OOP-МОДЕЛЬ',step:'Шаг',prev:'Назад',next:'Далее',reset:'Сбросить',type:'Модель типа',object:'Объект во время выполнения',iface:'Базовый интерфейс',privateState:'private-состояние',publicApi:'public-интерфейс',baseRef:'базовая ссылка',notBound:'не связана',dispatch:'virtual dispatch',experiment:'Свободный эксперимент',deposit:'deposit(+100)',withdraw:'withdraw(-50)',call:'view.kind()',direct:'bonus.balance = 0',blocked:'Отклонено: balance имеет private-доступ',same:'тот же объект',note:'Концептуальная модель'}}
export function oopLabMarkup(model,locale='ru'){
 if(!model?.steps?.length)return'';const L=labels(locale),s=model.steps[0];
 return `<section class="block oop-lab glass-panel" id="oopLab"><div class="oop-lab-head"><div><span class="eyebrow">${esc(L.eyebrow)}</span><h2>${esc(model.title||'OOP Model')}</h2><p>${esc(model.description||'')}</p></div><div class="oop-step-badge"><span>${esc(L.step)}</span><strong id="oopStepLabel">1/${model.steps.length}</strong></div></div>
 <div class="oop-stage">
  <article class="oop-node type-node active" id="oopTypeNode"><span>${esc(L.type)}</span><code>class Account</code><small>private balance · public deposit/withdraw/kind</small></article>
  <div class="oop-arrow" aria-hidden="true">→</div>
  <article class="oop-node object-node" id="oopObjectNode"><span>${esc(L.object)}</span><code id="oopObjectType">Account wallet</code><div class="oop-state-row"><small>${esc(L.privateState)}</small><strong id="oopBalance">${s.balance}</strong></div><div class="oop-state-row bonus" id="oopBonusRow"><small>bonusRate</small><strong id="oopBonusRate">—</strong></div></article>
  <div class="oop-arrow dispatch-arrow" aria-hidden="true">⇢</div>
  <article class="oop-node interface-node" id="oopInterfaceNode"><span>${esc(L.iface)}</span><code>Account&amp; view</code><strong id="oopBaseRef">${esc(L.notBound)}</strong><small id="oopDispatch">${esc(s.dispatch)}</small></article>
 </div>
 <div class="oop-explain"><strong id="oopStepTitle">${esc(s.title)}</strong><p id="oopStepExplanation">${esc(s.explanation)}</p><small>${esc(L.note)} · class/object/interface/dispatch</small></div>
 <div class="oop-controls"><button class="btn" id="oopPrev">${esc(L.prev)}</button><button class="btn primary" id="oopNext">${esc(L.next)}</button><button class="btn ghost" id="oopReset">${esc(L.reset)}</button></div>
 <div class="oop-freeplay"><span>${esc(L.experiment)}</span><div><button class="mini-action" id="oopDeposit">${esc(L.deposit)}</button><button class="mini-action" id="oopWithdraw">${esc(L.withdraw)}</button><button class="mini-action" id="oopCall">${esc(L.call)}</button><button class="mini-action danger" id="oopDirect">${esc(L.direct)}</button></div><small id="oopFreeStatus"></small></div></section>`;
}
export function bindOopLab(model,locale='ru'){
 if(!model?.steps?.length||!q('oopLab'))return;const L=labels(locale);let idx=0,freeBalance=null,lastMessage='';
 const render=()=>{const s=model.steps[idx];const balance=freeBalance===null?s.balance:freeBalance; q('oopStepLabel').textContent=`${idx+1}/${model.steps.length}`;q('oopStepTitle').textContent=s.title;q('oopStepExplanation').textContent=s.explanation;q('oopBalance').textContent=balance;q('oopBonusRate').textContent=s.derived?`${s.bonusRate}%`:'—';q('oopBonusRow').classList.toggle('active',!!s.derived);q('oopObjectType').textContent=s.derived?'BonusAccount bonus':'Account wallet';q('oopBaseRef').textContent=s.baseRef?'→ bonus':L.notBound;q('oopDispatch').textContent=s.baseRef?s.dispatch:'—';q('oopTypeNode').classList.toggle('active',true);q('oopObjectNode').classList.toggle('active',idx>=1);q('oopInterfaceNode').classList.toggle('active',!!s.baseRef);q('oopPrev').disabled=idx===0;q('oopNext').disabled=idx===model.steps.length-1;q('oopDeposit').disabled=idx<2;q('oopWithdraw').disabled=idx<2;q('oopCall').disabled=!s.baseRef;q('oopFreeStatus').textContent=lastMessage};
 q('oopPrev').onclick=()=>{idx=Math.max(0,idx-1);freeBalance=null;lastMessage='';render()};q('oopNext').onclick=()=>{idx=Math.min(model.steps.length-1,idx+1);freeBalance=null;lastMessage='';render()};q('oopReset').onclick=()=>{idx=0;freeBalance=null;lastMessage='';render()};q('oopDeposit').onclick=()=>{const s=model.steps[idx];freeBalance=(freeBalance===null?s.balance:freeBalance)+100;lastMessage=locale==='en'?`Public method preserved the invariant. balance = ${freeBalance}`:`Public-метод изменил состояние с сохранением инварианта. balance = ${freeBalance}`;render()};q('oopWithdraw').onclick=()=>{const s=model.steps[idx];const cur=freeBalance===null?s.balance:freeBalance;freeBalance=Math.max(0,cur-50);lastMessage=locale==='en'?`withdraw() changed state through the interface. balance = ${freeBalance}`:`withdraw() изменил состояние через интерфейс. balance = ${freeBalance}`;render()};q('oopCall').onclick=()=>{const s=model.steps[idx];lastMessage=locale==='en'?`Dynamic call selected: ${s.dispatch}`:`Динамический вызов выбрал: ${s.dispatch}`;render()};q('oopDirect').onclick=()=>{lastMessage=L.blocked;render()};render();
}
