import {codeStudioMarkup,bindCodeStudio} from '../sandbox/code-studio.js';
import {createSandboxController} from '../sandbox/sandbox.js';
import {getProject,patchProject,createCheckpoint,restoreCheckpoint,toggleProjectMilestone,deleteProject} from './project-store.js';

const e=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const fmt=value=>{try{return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}catch{return String(value||'')}};

export function projectStudioDashboardMarkup({projects=[],courseProjects=[],locale='ru'}={}){
  const en=locale==='en';
  const cards=projects.length?projects.map(project=>{const done=project.progress?.milestones?.length||0,total=project.origin?.courseProjectMilestones||0;return`<article class="ps-project-card glass-panel"><div class="ps-project-card-top"><span class="ps-language">${e((project.languageId||'').toUpperCase())}</span><span class="ps-sync local">${en?'LOCAL':'ЛОКАЛЬНО'}</span></div><h3>${e(project.title)}</h3><p>${e(project.description||'')}</p><div class="ps-project-meta"><span>${en?'Updated':'Изменён'} ${e(fmt(project.updatedAt))}</span>${total?`<span>${done}/${total} ${en?'stages':'этапов'}</span>`:''}</div><a class="btn primary" href="#view=project-studio&project=${encodeURIComponent(project.id)}">${en?'Continue':'Продолжить'}</a></article>`}).join(''):`<div class="ps-empty glass-panel"><strong>${en?'No projects yet':'Пока нет проектов'}</strong><span>${en?'Create a blank project or start from a C++ course project.':'Создайте пустой проект или начните с проекта курса C++.'}</span></div>`;
  const templates=(courseProjects||[]).map(project=>`<a class="ps-template-card" href="#view=project-studio&template=${encodeURIComponent('cpp:'+project.id)}"><span>${e(project.icon||'C++')}</span><div><strong>${e(project.title)}</strong><small>${e(project.pitch||'')}</small></div><b>→</b></a>`).join('');
  return `<section class="ps-hero glass-panel"><div><span class="eyebrow">NEXUS PROJECT STUDIO · FOUNDATION</span><h1>${en?'Build real projects inside Nexus':'Создавайте настоящие проекты внутри Nexus'}</h1><p>${en?'A project is now a first-class Nexus entity: manifest, folders, files, progress, checkpoints and the same Clang/WASM build pipeline used by Code Studio.':'Проект теперь полноценная сущность Nexus: manifest, папки, файлы, прогресс, checkpoints и тот же Clang/WASM build pipeline, который уже работает в Code Studio.'}</p><div class="hero-actions"><button class="btn primary" id="psNewProject">＋ ${en?'New project':'Новый проект'}</button><a class="btn" href="#view=programming">← ${en?'Programming':'Программирование'}</a></div></div><div class="ps-flow"><span>LEARN</span><i>→</i><span>CODE</span><i>→</i><span>PROJECT</span><i>→</i><span>RELEASE</span></div></section><section class="section ps-section"><div class="section-head"><div><span class="eyebrow">${en?'MY PROJECTS':'МОИ ПРОЕКТЫ'}</span><h2>${en?'Continue where you stopped':'Продолжить с того места, где остановились'}</h2></div></div><div class="ps-project-grid">${cards}</div></section><section class="section ps-section"><div class="section-head"><div><span class="eyebrow">C++ COURSE → PROJECT STUDIO</span><h2>${en?'Course projects':'Проекты курса'}</h2><p>${en?'Opening a course project creates a persistent Project Studio workspace without changing the source course content.':'Открытие проекта курса создаёт постоянный workspace Project Studio, не меняя исходный контент курса.'}</p></div></div><div class="ps-template-list">${templates}</div></section><section class="ps-roadmap glass-panel"><div><strong>Nexus Sync</strong><span>${en?'Foundation prepared · cross-device cloud sync is the next layer.':'Модель подготовлена · облачная синхронизация между устройствами — следующий слой.'}</span></div><div><strong>Export & Release</strong><span>${en?'Project manifest is export-ready · source ZIP/build artifacts come next.':'Manifest проекта готов к экспорту · ZIP исходников и build artifacts будут следующим этапом.'}</span></div></section>`;
}

export function projectStudioViewMarkup({project,courseProject=null,locale='ru'}={}){
  const en=locale==='en';if(!project)return'';
  const milestones=courseProject?.milestones||[];const done=new Set(project.progress?.milestones||[]);const checkpoints=project.checkpoints||[];
  const workspace=project.workspace||{};const files=workspace.files||[];const active=workspace.activeFile||project.manifest?.entryFile||files[0]?.path||'src/main.cpp';const activeFile=files.find(x=>x.path===active)||files[0];
  const milestoneMarkup=milestones.length?milestones.map((m,i)=>`<label class="ps-milestone ${done.has(i)?'done':''}"><input type="checkbox" data-ps-milestone="${i}" ${done.has(i)?'checked':''}><span><strong>${e(m.t)}</strong><small>${e(m.d)}</small></span></label>`).join(''):`<div class="ps-note">${en?'Free project: define your own stages and use checkpoints as stable milestones.':'Свободный проект: этапы определяете вы, а checkpoints можно использовать как стабильные контрольные точки.'}</div>`;
  const checkpointMarkup=checkpoints.length?checkpoints.map(c=>`<button type="button" class="ps-checkpoint" data-ps-restore="${e(c.id)}"><span>◉</span><div><strong>${e(c.label)}</strong><small>${e(fmt(c.createdAt))}</small></div></button>`).join(''):`<div class="ps-note compact">${en?'No checkpoints yet.':'Checkpoint пока нет.'}</div>`;
  return `<a class="back-link" href="#view=project-studio">← Project Studio</a><section class="ps-project-head glass-panel"><div><span class="eyebrow">PROJECT · ${e((project.languageId||'cpp').toUpperCase())}</span><h1>${e(project.title)}</h1><p>${e(project.description||'')}</p><div class="ps-badges"><span>LOCAL-FIRST</span><span>${e(project.manifest?.build?.standard||'')}</span><span>${e(project.manifest?.build?.profile||'')}</span><span>${en?'SYNC NEXT':'SYNC NEXT'}</span></div></div><div class="ps-project-actions"><button class="btn primary" id="psCheckpoint">◎ ${en?'Checkpoint':'Checkpoint'}</button><button class="btn" id="psRenameProject">✎ ${en?'Rename':'Переименовать'}</button><button class="btn danger" id="psDeleteProject">× ${en?'Delete':'Удалить'}</button></div></section><div class="ps-layout"><aside class="ps-side"><section class="ps-panel glass-panel"><span class="eyebrow">MANIFEST</span><dl><div><dt>entry</dt><dd>${e(project.manifest?.entryFile)}</dd></div><div><dt>runtime</dt><dd>${e(project.manifest?.build?.runtime)}</dd></div><div><dt>sync</dt><dd>${en?'local only':'локально'}</dd></div><div><dt>release</dt><dd>${e(project.release?.status||'draft')}</dd></div></dl></section><section class="ps-panel glass-panel"><span class="eyebrow">${en?'STAGES':'ЭТАПЫ'}</span><div class="ps-milestones">${milestoneMarkup}</div></section><section class="ps-panel glass-panel"><span class="eyebrow">CHECKPOINTS</span><div class="ps-checkpoints">${checkpointMarkup}</div></section></aside><section class="ps-workbench glass-panel"><div class="codebox"><div class="codehead"><span id="codeFileLabel">${e(active)}</span><div class="runtime-head"><span id="runtimeRoute" class="runtime-route idle">AUTO · ${e((project.languageId||'cpp').toUpperCase())}</span><span id="engine" class="engine-status idle">${en?'Nexus Runtime · ready to load':'Nexus Runtime · готов к загрузке'}</span></div></div><div class="sandbox-status" id="sandboxStatus"><span>● ${en?'Project analysis':'Анализ проекта'}: —</span><span>${en?'Runtime: not run':'Runtime: не запускался'}</span></div>${codeStudioMarkup({source:activeFile?.content||'',files,activeFile:active,entryFile:project.manifest?.entryFile||'src/main.cpp',locale,languageId:project.languageId||'cpp'})}<label class="stdin-label">${en?'Standard input (stdin)':'Стандартный ввод (stdin)'}<textarea id="stdin" class="stdin" autocapitalize="off" autocomplete="off" autocorrect="off">${e(project.stdin||'')}</textarea></label><div class="runrow"><button id="runCode" class="btn primary">${en?'▶ Run project':'▶ Запустить проект'}</button><button id="testRuntime" class="btn">${en?'✓ Test runtime':'✓ Проверить среду'}</button><button id="clearOutput" class="btn">${en?'Clear output':'Очистить вывод'}</button></div><div id="output" class="output">${en?'Project output will appear here.':'Вывод проекта появится здесь.'}</div></div></section></div>`;
}

export function bindProjectStudio({projectId,locale='ru',onChanged=()=>{},onDeleted=()=>{}}={}){
  const project=getProject(projectId);if(!project)return null;const en=locale==='en';const editor=document.querySelector('#editor');if(!editor)return null;
  const studio=bindCodeStudio({editor,locale,languageId:project.languageId||'cpp',fileName:project.manifest?.entryFile||'src/main.cpp',files:project.workspace?.files||[],activeFile:project.workspace?.activeFile||project.manifest?.entryFile,viewState:project.workspace?.viewState||null,onWorkspaceChange:snapshot=>{patchProject(projectId,{workspace:snapshot});onChanged()}});
  const stdin=document.querySelector('#stdin'),output=document.querySelector('#output'),engine=document.querySelector('#engine'),status=document.querySelector('#sandboxStatus'),routeInfo=document.querySelector('#runtimeRoute');
  const controller=createSandboxController({editor,stdin,output,engine,status,routeInfo,requirements:[],locale,languageId:project.languageId||'cpp',codeStudio:studio,onCodeChange:()=>{}});
  stdin?.addEventListener('input',()=>patchProject(projectId,{stdin:stdin.value}));
  document.querySelector('#runCode')?.addEventListener('click',()=>controller.run().catch(()=>{}));
  document.querySelector('#testRuntime')?.addEventListener('click',()=>controller.selfTest().catch(()=>{}));
  document.querySelector('#clearOutput')?.addEventListener('click',()=>{studio?.clearRuntimeDiagnostics?.();output.className='output';output.textContent=en?'Project output will appear here.':'Вывод проекта появится здесь.'});
  document.querySelectorAll('[data-ps-milestone]').forEach(box=>box.addEventListener('change',()=>{toggleProjectMilestone(projectId,Number(box.dataset.psMilestone),box.checked);box.closest('.ps-milestone')?.classList.toggle('done',box.checked);onChanged()}));
  document.querySelector('#psCheckpoint')?.addEventListener('click',()=>{const label=prompt(en?'Checkpoint name':'Название checkpoint',en?'Working state':'Рабочее состояние');if(!label)return;createCheckpoint(projectId,label);onChanged(true)});
  document.querySelectorAll('[data-ps-restore]').forEach(btn=>btn.addEventListener('click',()=>{if(!confirm(en?'Restore this checkpoint? Current files will be replaced.':'Восстановить этот checkpoint? Текущие файлы будут заменены.'))return;restoreCheckpoint(projectId,btn.dataset.psRestore);onChanged(true)}));
  document.querySelector('#psRenameProject')?.addEventListener('click',()=>{const current=getProject(projectId);const title=prompt(en?'Project name':'Название проекта',current?.title||'');if(!title?.trim())return;patchProject(projectId,{title:title.trim(),manifest:{title:title.trim()}});onChanged(true)});
  document.querySelector('#psDeleteProject')?.addEventListener('click',()=>{if(!confirm(en?'Delete this local project?':'Удалить этот локальный проект?'))return;deleteProject(projectId);onDeleted()});
  return{studio,controller};
}
