const PROJECTS_KEY='akronikl:it-nexus:projects:v1';

const now=()=>new Date().toISOString();
const clone=value=>JSON.parse(JSON.stringify(value));
const safeId=value=>String(value||'project').trim().toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'project';
const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;

function storage(){return globalThis.localStorage||null}
function parse(raw,fallback){try{return raw?JSON.parse(raw):fallback}catch{return fallback}}
function defaultDb(){return{schemaVersion:1,projects:{},updatedAt:null}}

export function loadProjectDb(){const db=parse(storage()?.getItem(PROJECTS_KEY),defaultDb());return{...defaultDb(),...db,projects:{...(db?.projects||{})}}}
export function saveProjectDb(db){const next={...db,updatedAt:now()};storage()?.setItem(PROJECTS_KEY,JSON.stringify(next));return next}
export function listProjects(){return Object.values(loadProjectDb().projects).sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))).map(clone)}
export function getProject(id){const item=loadProjectDb().projects?.[id];return item?clone(item):null}
export function putProject(project){if(!project?.id)throw new Error('Project id is required.');const db=loadProjectDb();const prev=db.projects[project.id];const stamp=now();const next={...clone(project),createdAt:project.createdAt||prev?.createdAt||stamp,updatedAt:stamp};next.manifest={schemaVersion:1,...next.manifest,id:next.id,title:next.title,languageId:next.languageId||next.manifest?.languageId||'cpp',updatedAt:stamp};next.sync={...(prev?.sync||{}),...(next.sync||{}),mode:next.sync?.mode||prev?.sync?.mode||'local-only',status:'local',revision:Number(next.sync?.revision??prev?.sync?.revision??0)+1,lastLocalChangeAt:stamp};db.projects[next.id]=next;saveProjectDb(db);return clone(next)}
export function patchProject(id,patch){const current=getProject(id);if(!current)throw new Error(`Project not found: ${id}`);const next={...current,...clone(patch)};if(patch?.manifest)next.manifest={...current.manifest,...clone(patch.manifest)};if(patch?.workspace)next.workspace=clone(patch.workspace);if(patch?.progress)next.progress={...current.progress,...clone(patch.progress)};if(patch?.release)next.release={...current.release,...clone(patch.release)};return putProject(next)}
export function deleteProject(id){const db=loadProjectDb();if(!db.projects[id])return false;delete db.projects[id];saveProjectDb(db);return true}
export function createProject(input={}){const title=String(input.title||'Новый проект').trim()||'Новый проект';const id=input.id||uid(safeId(title));const languageId=input.languageId||'cpp';const entryFile=input.entryFile||'src/main.cpp';const files=Array.isArray(input.files)&&input.files.length?input.files:[{path:entryFile,content:'#include <iostream>\n\nint main() {\n    std::cout << "Hello, Nexus!\\n";\n    return 0;\n}\n',languageId}];const project={id,title,languageId,description:String(input.description||''),origin:clone(input.origin||{kind:'user'}),manifest:{schemaVersion:1,id,title,languageId,entryFile,sourceRoots:input.sourceRoots||['src'],includeRoots:input.includeRoots||['include'],testRoots:input.testRoots||['tests'],build:{profile:'wasm-debug',standard:languageId==='cpp'?'c++20':'default',runtime:'auto'},sync:{strategy:'local-first',cloud:'planned'},release:{status:'draft'}},workspace:{languageId,entryFile,activeFile:input.activeFile||entryFile,revision:0,files:clone(files),viewState:null},progress:{milestones:[],tests:{passed:0,total:0},stage:'draft'},checkpoints:[],sync:{mode:'local-only',status:'local',revision:0},release:{status:'draft',artifacts:[]}};return putProject(project)}
export function ensureTemplateProject({templateKey,title,description='',languageId='cpp',entryFile='src/main.cpp',files=[],origin={},manifest={},progress={}}={}){if(!templateKey)throw new Error('templateKey is required');const existing=listProjects().find(item=>item.origin?.templateKey===templateKey);if(existing)return existing;const created=createProject({id:`template-${safeId(templateKey)}`,title,description,languageId,entryFile,files,origin:{...origin,templateKey},sourceRoots:manifest.sourceRoots,includeRoots:manifest.includeRoots,testRoots:manifest.testRoots,activeFile:entryFile});return Object.keys(progress||{}).length?patchProject(created.id,{progress:{...created.progress,...clone(progress)}}):created}
export function createCheckpoint(projectId,label='Checkpoint'){const project=getProject(projectId);if(!project)throw new Error(`Project not found: ${projectId}`);const checkpoint={id:uid('checkpoint'),label:String(label||'Checkpoint').trim()||'Checkpoint',createdAt:now(),workspace:clone(project.workspace),progress:clone(project.progress),release:clone(project.release)};const checkpoints=[checkpoint,...(project.checkpoints||[])].slice(0,30);return patchProject(projectId,{checkpoints})}
export function restoreCheckpoint(projectId,checkpointId){const project=getProject(projectId);if(!project)throw new Error(`Project not found: ${projectId}`);const checkpoint=(project.checkpoints||[]).find(item=>item.id===checkpointId);if(!checkpoint)throw new Error(`Checkpoint not found: ${checkpointId}`);return patchProject(projectId,{workspace:clone(checkpoint.workspace),progress:clone(checkpoint.progress),release:clone(checkpoint.release)})}
export function toggleProjectMilestone(projectId,index,value){const project=getProject(projectId);if(!project)throw new Error(`Project not found: ${projectId}`);const done=new Set(project.progress?.milestones||[]);value?done.add(Number(index)):done.delete(Number(index));return patchProject(projectId,{progress:{...project.progress,milestones:[...done].sort((a,b)=>a-b)}})}
export function projectStorageKey(){return PROJECTS_KEY}
